export const navigation = [
    {
      id: "0",
      title: "Home",
      url: "#home",
    },
    {
      id: "1",
      title: "Pricing",
      url: "#pricing",
    },
    {
      id: "2",
      title: "How it works",
      url: "#how-it-works",
    },
    {
      id: "3",
      title: "FAQ",
      url: "#faq",
    },
    {
      id: "4",
      title: "New account",
      url: "#signup",
      onlyMobile: true,
    },
    {
      id: "5",
      title: "Sign in",
      url: "#login",
      onlyMobile: true,
    },
  ];

  export const images = {
    yourlogo: "/assets/yourlogo.svg",
    brainwave: "/assets/brainwave.svg",
    check: "/assets/check.svg",
    check2: "/assets/check-02.svg",
    loading1: "/assets/loading-01.svg",
    brainwaveSymbol: "/assets/brainwave-symbol.svg",
    brainwaveWhiteSymbol: "/assets/brainwave-symbol-white.svg",
    play: "/assets/play.svg",
    gradient: "/assets/gradient.png",
    smallSphere: "/assets/4-small.png",
    grid: "/assets/grid.png",
    homeSmile: "/assets/home-smile.svg",
    file02: "/assets/file-02.svg",
    searchMd: "/assets/search-md.svg",
    plusSquare: "/assets/plus-square.svg",
    recording03: "/assets/recording-03.svg",
    recording01: "/assets/recording-01.svg",
    disc02: "/assets/disc-02.svg",
    chromecast: "/assets/chrome-cast.svg",
    sliders04: "/assets/sliders-04.svg",
    loading: "/assets/loading.png",
    background: "/assets/background.jpg",
    curve: "/assets/hero/curve.png",
    robot: "/assets/hero/robot.jpg",
    heroBackground: "/assets/hero/hero-background.jpg",
    curve1: "/assets/collaboration/curve-1.svg",
    curve2: "/assets/collaboration/curve-2.svg",
    discord: "/assets/collaboration/discord.png",
    figma: "/assets/collaboration/figma.png",
    framer: "/assets/collaboration/framer.png",
    notion: "/assets/collaboration/notion.png",
    photoshop: "/assets/collaboration/photoshop.png",
    protopie: "/assets/collaboration/protopie.png",
    raindrop: "/assets/collaboration/raindrop.png",
    slack: "/assets/collaboration/slack.png",
    service1: "/assets/services/service-1.png",
    service2: "/assets/services/service-2.png",
    service3: "/assets/services/service-3.png",
    lines: "/assets/pricing/lines.svg",
    stars: "/assets/pricing/stars.svg",
    coins: "/assets/roadmap/coins.png",
    done: "/assets/roadmap/done.svg",
    hero: "/assets/roadmap/hero.png",
    roadmap1: "/assets/roadmap/image-1.png",
    roadmap2: "/assets/roadmap/image-2.png",
    roadmap3: "/assets/roadmap/image-3.png",
    roadmap4: "/assets/roadmap/image-4.png",
    undone: "/assets/roadmap/undone.svg",
    notification1: "/assets/notification/image-1.png",
    notification2: "/assets/notification/image-2.png",
    notification3: "/assets/notification/image-3.png",
    notification4: "/assets/notification/image-4.png",
    benefitCard1: "/assets/benefits/card-1.svg",
    benefitCard2: "/assets/benefits/card-2.svg",
    benefitCard3: "/assets/benefits/card-3.svg",
    benefitCard4: "/assets/benefits/card-4.svg",
    benefitCard5: "/assets/benefits/card-5.svg",
    benefitCard6: "/assets/benefits/card-6.svg",
    benefitIcon1: "/assets/benefits/icon-1.svg",
    benefitIcon2: "/assets/benefits/icon-2.svg",
    benefitIcon3: "/assets/benefits/icon-3.svg",
    benefitIcon4: "/assets/benefits/icon-4.svg",
    benefitImage2: "/assets/benefits/image-2.png",
    discordBlack: "/assets/socials/discord.svg",
    facebook: "/assets/socials/facebook.svg",
    instagram: "/assets/socials/instagram.svg",
    telegram: "/assets/socials/telegram.svg",
    twitter: "/assets/socials/twitter.svg",
  };